BARCODE_V7 = (  'cg', 'GATACGATACGCGCACGCTATGG',
      'agtc', 'GACACGACTCGCGCATACGATGG',
      'agtc', 'GATAGTATGCGTATACGCTATGG',
      'agtc', 'GATATGCATAGCGCATGCTATGG',
      'agtc', 'GAGTCGAGACGCTGACGATATGG',
      'agtc', 'GCTACGATACACTCTGACTATGG',
      'agtc', 'GCGACTGTACGCACACGCGATGG',
      'agtc', 'GATACGTAGCACGCAGACTATGG',
      'agtc', 'GACACAGTACTCTCACTCTATGG',
      'agtc', 'GATATGAGACTCGCATGTGATGG',
      'ga')

NUM_BARCODE_V7_TARGETS = int(len(BARCODE_V7)/2)
BARCODE_V7_LEN = len("".join(BARCODE_V7))

NO_EVENT_STRS = ["NONE", "UNKNOWN"]

CONTROL_ORGANS = ["7B_1_to_500_blood", "7B_1_to_20_blood", "7B_1_to_100_blood"]
