#!/usr/bin/env scons

# Simulate data under various different settings and fit models

import os

from os.path import join
from nestly.scons import SConsWrap
from nestly import Nest
import SCons.Script as sc

# Command line options

sc.AddOption('--clusters', type='string', help="Clusters to submit to. Default is local execution.", default='')
sc.AddOption('--output', type='string', help="output folder", default='_output')

env = sc.Environment(
        ENV=os.environ,
        clusters=sc.GetOption('clusters'),
        output=sc.GetOption('output'))

sc.Export('env')

env.SConsignFile()

flag = 'simulation_sanity'
sc.SConscript(flag + '/sconscript', exports=['flag'])

flag = 'simulation_topol_consist'
sc.SConscript(flag + '/sconscript', exports=['flag'])

flag = 'simulation_compare'
sc.SConscript(flag + '/sconscript', exports=['flag'])

flag = 'simulation_replicate_real_data'
sc.SConscript(flag + '/sconscript', exports=['flag'])

flag = 'analyze_gestalt'
SConscript(flag + '/sconscript', exports=['flag'])


#flag = 'simulation_consistency'
#SConscript(flag + '/sconscript', exports=['flag'])
#flag = 'simulation_topology_same_diff'
#SConscript(flag + '/sconscript', exports=['flag'])
#
#flag = 'simulation_topology_random_vs_sorted'
#SConscript(flag + '/sconscript', exports=['flag'])
#
#flag = 'simulation_topology_sampling'
#SConscript(flag + '/sconscript', exports=['flag'])
#
#flag = 'simulation_topology_magnitude'
#SConscript(flag + '/sconscript', exports=['flag'])
#
#flag = 'simulation_topology_double'
#SConscript(flag + '/sconscript', exports=['flag'])
#
#flag = 'simulation_one_barcode'
#SConscript(flag + '/sconscript', exports=['flag'])
